# -*- coding: utf-8 -*-
"""Praktikum3_AnalisisAlgoritma_Andika Pratama_G.211.25.0061.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbmvdqMzwDS6S2_xzJOg4fqtOcjNR_xX

fungsi dijkstra(graf, start):

    Buat dict jarak, isi semua node dengan nilai tak terhingga (inf)
    
    Set jarak[start] = 0

    Buat priority queue (min-heap), masukkan (0, start)
    
    Buat dict sebelumnya = {} untuk menyimpan jalur

    if priority queue tidak kosong:
          Ambil node dengan jarak terkecil (curr_dist, curr_node)
         if curr_dist > jarak[curr_node]: LEWATI (sudah usang)
          UNTUK setiap tetangga (neighbor, bobot) dari curr_node:
            hitung jarak_baru = jarak[curr_node] + bobot
           if jarak_baru < jarak[neighbor]:
                Update jarak[neighbor] = jarak_baru
                Simpan sebelumnya[neighbor] = curr_node
                Masukkan (jarak_baru, neighbor) ke priority queue

        Return jarak, sebelumnya

    fungsi rekonstruksi_jalur(sebelumnya, start, end):
        Buat list jalur = []
        node = end
        SELAMA node ada di dict sebelumnya:
       tambahkan node ke jalur
       node = sebelumnya[node]
        Tambahkan start ke jalur
        Balik urutan jalur
        return jalur **teks tebal** teks tebal
"""

import heapq
import math


def dijkstra(graf, start):
    """
    Mencari jarak terpendek dari node 'start' ke semua node lain.

    Parameter:
        graf  : dict berupa adjacency list {node: [(tetangga, bobot), ...]}
        start : node awal

    Return:
        jarak     : dict jarak terpendek ke setiap node
        sebelumnya: dict untuk rekonstruksi jalur
    """

    jarak = {node: math.inf for node in graf}
    jarak[start] = 0


    pq = [(0, start)]


    sebelumnya = {}


    while pq:
        curr_dist, curr_node = heapq.heappop(pq)


        if curr_dist > jarak[curr_node]:
            continue


        for tetangga, bobot in graf[curr_node]:
            jarak_baru = jarak[curr_node] + bobot

            if jarak_baru < jarak[tetangga]:
                jarak[tetangga] = jarak_baru
                sebelumnya[tetangga] = curr_node
                heapq.heappush(pq, (jarak_baru, tetangga))

    return jarak, sebelumnya


def rekonstruksi_jalur(sebelumnya, start, end):
    """Merekonstruksi jalur dari start ke end."""
    jalur = []
    node = end
    while node in sebelumnya:
        jalur.append(node)
        node = sebelumnya[node]
    jalur.append(start)
    jalur.reverse()
    return jalur if jalur[0] == start else []



graf = {
    'A': [('B', 4), ('C', 2)],
    'B': [('A', 4), ('C', 5), ('D', 10)],
    'C': [('A', 2), ('B', 5), ('D', 3), ('E', 8)],
    'D': [('B', 10), ('C', 3), ('E', 2)],
    'E': [('C', 8), ('D', 2)],
}

start_node = 'A'
jarak, sebelumnya = dijkstra(graf, start_node)

print(f"SHORTEST PATH dari node '{start_node}'")
print(f"{'Node':<10} {'Jarak':<10} {'Jalur'}")
print("-" * 40)

for node in sorted(graf.keys()):
    if node == start_node:
        print(f"  {node:<9} {0:<10} [{start_node}]")
    else:
        jalur = rekonstruksi_jalur(sebelumnya, start_node, node)
        jalur_str = " -> ".join(jalur)
        print(f"  {node:<9} {jarak[node]:<10} [{jalur_str}]")

"""Analisa Kompleksitas Waktu



Inisialisasi = O(V)

heappush/heappopO = (log V)

Cek semua edge = O(E)

TOTALO((V + E) log V)
"""